version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
<<<<<<
 add_dependabot
      khoảng thời gian : "hàng ngày"   ======= 
      interval: "daily"
 chính
======
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
>>>>> 
