# See: https://yamllint.readthedocs.io/en/stable/

rules:
  document-end: enable
  document-start:
    level: warning
    present: true
  line-length:
    level: warning
    max: 80
    allow-non-breakable-words: false
    allow-non-breakable-inline-mappings: false
