name: 'PR comment'
description: 'Adds PR changes as comment'
inputs:
  owner: 
    description: 'The owner of the repository'
    required: true
  repo:
    description: "The repository name"
    required: true
  pr_number:
    description: "The number of the pull request"
    required: true
  token:
    description: "The token to use to access the Github API"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
