name: 'StarTeknoloji' 
description: 'HOŞGELDİNİZ' 
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs: 
  using: 'node16'
  main: 'dist/index.js'
simge: book-open
renk:  black
